version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      # use environment variables for example ${DB_NAME}

      POSTGRES_DB: "auto_park"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"